apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-scripts
data:
  init-history.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.mariadb.MYSQL_MOOVAPPS_HISTORY_DATABASE_NAME }};
  init-report.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.mariadb.MYSQL_MOOVAPPS_REPORT_DATABASE_NAME }};
