apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mariadb.replicas }}
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.repository }}:{{ .Values.mariadb.tag }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.MYSQL_MOOVAPPS_DATABASE_PASSWORD }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.MYSQL_MOOVAPPS_DATABASE_NAME }}
            - name: MYSQL_ROOT_HOST
              value: '%'
          ports:
          - containerPort: 3306
          readinessProbe:
            exec:
              command:
                - "mysqladmin"
                - "ping"
                - "--silent"
            initialDelaySeconds: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - "mysqladmin"
                - "ping"
                - "--silent"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
          - name: moovapps-database
            mountPath: /var/lib/mysql
          
      volumes:
      - name: moovapps-database
        hostPath:
          path: /usr/share/mariadb/