apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moveapps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: moveapps-ingress
  namespace: "{{ .Values.namespace }}"
spec:
  rules:
  - host: "{{ .Values.host }}"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: moveapps-service
              port:
                number: 8080