apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moveapps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: lets-encrypt
  labels:
    app: moveapps-ingress
  namespace: "{{ .Values.namespace }}"
spec:
  tls:
    - hosts:
      {{- range .Values.hosts }}
      - {{ . }}
      {{- end }}
      secretName: moveapps-ingress-tls
  rules:
  {{- range .Values.hosts }}
  - host: {{ . }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: moveapps-service
              port:
                number: 8080
  {{- end }}