apiVersion: v1
kind: Service
metadata:
  name: maildev
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: maildev
  ports:
    - protocol: TCP
      port: {{ .Values.maildev.MAILDEV_WEBAPP_PORT }}
      targetPort: {{ .Values.maildev.MAILDEV_WEBAPP_PORT }}
      name: webapp
    - protocol: TCP
      port: {{ .Values.maildev.MAILDEV_SMTP_PORT }}
      targetPort: {{ .Values.maildev.MAILDEV_SMTP_PORT }}
      name: smtp
  type: ClusterIP # Change to LoadBalancer if using a cloud provider
